FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN mkdir -p /var/secrets

EXPOSE 8080

CMD sh -c 'uvicorn admin_api:app --host 0.0.0.0 --port ${PORT:-8080}'
